### ISSUE TITLE
Album covers won't work and show unavailable image icon

### ISSUE THREAD

**Issue by tobimori** [ljosberinn/historic-lastfm#73]
![image](https://user-images.githubusercontent.com/29142128/86587272-9a65a980-bf89-11ea-866b-3f9410ad8fe6.png)

**Comment by ljosberinn** [comment]
covers: unfixeable, lastfm doesnt respond with correct images for whatever reason
play button: thats an error indeed

**Comment by tobimori** [comment]
Ah, I thought the error icon was for the cover, my bad!
